spring:
    profiles:
        active: dev
    devtools:
        restart:
            enabled: true
    jpa:
        show-sql: true
        open-in-view: false

mybatis-plus:
    mapper-locations: classpath:/mapper/*Mapper.xml
    configuration:
        #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
        cache-enabled: false
