spring:
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL57Dialect
        show-sql: true
        hbm2ddl:
          auto: update

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.234.46.152:3306/jdw?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: root
    password: a26af&*&*^G3=sj

logging:
  level:
    org:
      springframework:
        security: TRACE